services:
  postgres:
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=airbnb-clone
      - POSTGRES_PASSWORD=password
      - POSTGRES_USER=postgres
    ports:
      - 5434:5432
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
